#!/usr/bin/env bash
# advance task

IFS=$'\n' read -d '' -r -a lines < /etc/passwd
nb_lines=${#lines[*]}
i=0
while [ $i -lt "$nb_lines" ]; do
	line=${lines[i]}
	user=$(echo "$line" | cut -d ':' -f1)
	pass=$(echo "$line" | cut -d ':' -f2)
	id=$(echo "$line" | cut -d ':' -f3)
	grp=$(echo "$line" | cut -d ':' -f4)
	usr_id_info=$(echo "$line" | cut -d ':' -f5)
	home=$(echo "$line" | cut -d ':' -f6)
	shell=$(echo "$line" | cut -d ':' -f7)
	echo "The user $user is part of the $grp gang, lives in $home and rides $shell. $id's place is protected by the passcode $pass, more info about the user here: $usr_id_info"
	let i+=1
done
